name: Clang-Format

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  clang_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run clang format
        run: |
          sudo apt update
          sudo apt install -y git clang-format
          if [ $? -ge 1 ]; then return 1; fi
          ./.run-clang-format
          if [ $? -ge 1 ]; then return 1; fi
          output=$(git diff)
          if [ -n "$output" ]; then exit 1; else exit 0; fi
