name: Ubuntu-Focal

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  ci:
    name: Ubuntu-Focal
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: workspace/src/boost_plugin_loader

      - name: Install dependencies
        working-directory: workspace
        run: |
          pwd
          sudo apt update -q
          sudo apt install -q -y clang-tidy python3 python3-pip
          sudo pip3 install -q --upgrade pip
          sudo pip3 install -q colcon-common-extensions rosdep vcstool
          sudo rosdep init -q
          rosdep update -q
          vcs import --input "${{ github.workspace }}/workspace/src/boost_plugin_loader/dependencies.repos" src/
          rosdep install --from-paths src --ignore-src -r -y -q

      - name: Build
        working-directory: workspace
        run: |
          colcon build --event-handlers console_direct+ --cmake-args -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DENABLE_CLANG_TIDY=ON -DENABLE_CODE_COVERAGE=ON
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Test
        working-directory: workspace
        run: |
          colcon test --event-handlers console_direct+ --return-code-on-test-failure
          colcon test-result

      - name: CodeCov
        working-directory: workspace
        run: |
          source install/setup.bash
          make -C ./build/boost_plugin_loader ccov-all
          bash <(curl -s https://codecov.io/bash) -t ec6ee46b-1f52-482c-82ef-1aaabc673f8d -s ./build/boost_plugin_loader -f *all-merged.info
