name: Windows-2019

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  windows_ci:
    name: Windows-2019
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        path: workspace/src/boost_plugin_loader

    - name: install-depends
      working-directory: workspace
      shell: cmd
      run: |
        python -m pip install vcstool -q
        python -m pip install colcon-common-extensions -q
        python -m pip install ninja -q
        mkdir install
        nuget install ${{ github.workspace }}/workspace/src/boost_plugin_loader/packages.config -OutputDirectory ${{ github.workspace }}/workspace/install -ExcludeVersion
        dir install
        dir install/boost
        dir install/boost_filesystem-vc140

    - name: configure-msvc
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: build-workspace
      working-directory: workspace
      shell: cmd
      run: |
        vcs import --input "${{ github.workspace }}/workspace/src/boost_plugin_loader/dependencies.repos" src/
        colcon build --event-handlers console_direct+ --cmake-args -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        if %ERRORLEVEL% GEQ 1 exit 1

    - name: run-test
      working-directory: workspace
      shell: cmd
      run: |
        colcon test --event-handlers console_direct+ --return-code-on-test-failure
        colcon test-result --verbos
